Postcode error handling
mysociety/contract-countdown pull request #23
Opened 2022-09-27 08:29 UTC by alexander-griffen

When the postcode is entered, validation occurs as part of the `clean` function of the form.

The postcode validation is the same as that in CAPE.

Also, validation errors for that field have been added to the html template.

2022-09-28 08:58 UTC, struan requested changes
One small issue with the postcode widget but the rest looks good.

The only thing that would be good is it currently just ignores various exceptions in the mapit call and those should probably get handled. Certainly the NotFoundException which is thrown if you put in a postcode that is valid but doesn't exist, e.g. KY34 9QZ

2022-09-28 08:58 UTC, struan commented on procurement/forms.py
> +        )
I don't totally understand why but it looks like the widget stuff here is overridden by the filter so none of this applies. It does seem to work if you move the widget stuff to the filter.

2022-09-29 21:03 UTC, alexander-griffen commented on procurement/forms.py
> +        )
This has now been moved back to the filter, and works

2022-09-29 21:05 UTC, alexander-griffen commented
> One small issue with the postcode widget but the rest looks good.
> 
> The only thing that would be good is it currently just ignores various exceptions in the mapit call and those should probably get handled. Certainly the NotFoundException which is thrown if you put in a postcode that is valid but doesn't exist, e.g. KY34 9QZ

This has been achieved - albeit slightly jankily - by moving the logic of the mapit call to the validation step, so that errors can be caught.

2022-10-10 12:57 UTC, struan approved these changes
Probably should get the postcode stuff this is based on merged first and then rebase and merge this, but looks good.

2022-10-10 12:57 UTC, struan commented on procurement/views.py
> +            .filter(state="complete")
There's a typo in this commit message :)

2022-10-10 12:57 UTC, struan commented on procurement/templates/procurement/home.html
> -
Could probably squash this and the change to `tender_filter` into the previous commit for tidyness.

2022-10-14 13:41 UTC, zarino commented
This branch was merged straight into `master` :+1:

2022-10-14 13:41 UTC, closed without merging